# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'CapCoreValidator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CapCoreValidator
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '8.10.0'

end
